import { Medicine } from "@/types/medicine";

export const CATEGORIES = [
  "Antibióticos",
  "Anti-inflamatórios",
  "Vitaminas",
  "Analgésicos",
  "Dermatológicos",
  "Cardiovasculares"
];

export const MEDICINES: Medicine[] = [
  {
    id: "1",
    nome: "Amoxicilina 500mg",
    principioAtivo: "Amoxicilina",
    categoria: "Antibióticos",
    preco: 45.90,
    estoque: 15,
    imagem: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Antibiótico eficaz contra diversas infecções bacterianas.",
    modoUso: "Tomar 1 cápsula a cada 8 horas por 7 dias.",
    contraindicacoes: "Hipersensibilidade a penicilinas.",
    rating: 4.5,
    criadoEm: new Date().toISOString(),
  },
  {
    id: "2",
    nome: "Ibuprofeno 600mg",
    principioAtivo: "Ibuprofeno",
    categoria: "Anti-inflamatórios",
    preco: 22.50,
    estoque: 50,
    imagem: "https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Indicado para alívio de dores e inflamações.",
    modoUso: "1 comprimido a cada 12 horas.",
    contraindicacoes: "Úlcera gastroduodenal ativa.",
    rating: 4.8,
    criadoEm: new Date().toISOString(),
  },
  {
    id: "3",
    nome: "Vitamina C 1g",
    principioAtivo: "Ácido Ascórbico",
    categoria: "Vitaminas",
    preco: 15.00,
    estoque: 100,
    imagem: "https://images.unsplash.com/photo-1616671285410-9a000969499f?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Suplemento vitamínico para reforço do sistema imunológico.",
    modoUso: "Dissolver 1 comprimido efervescente em água uma vez ao dia.",
    contraindicacoes: "Cálculos renais recorrentes.",
    rating: 4.9,
    criadoEm: new Date().toISOString(),
  },
  {
    id: "4",
    nome: "Paracetamol 750mg",
    principioAtivo: "Paracetamol",
    categoria: "Analgésicos",
    preco: 12.90,
    estoque: 0,
    imagem: "https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Analgésico e antitérmico de uso comum.",
    modoUso: "1 comprimido a cada 6 horas se necessário.",
    contraindicacoes: "Doença hepática grave.",
    rating: 4.2,
    criadoEm: new Date().toISOString(),
  },
  {
    id: "5",
    nome: "Dipirona Sódica 500mg",
    principioAtivo: "Dipirona",
    categoria: "Analgésicos",
    preco: 8.50,
    estoque: 80,
    imagem: "https://images.unsplash.com/photo-1471864190281-a93a307246de?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Medicamento para dor e febre.",
    modoUso: "1 a 2 comprimidos até 4 vezes ao dia.",
    contraindicacoes: "Alergia a pirazolonas.",
    rating: 4.6,
    criadoEm: new Date().toISOString(),
  },
  {
    id: "6",
    nome: "Complexo B",
    principioAtivo: "Vitaminas do Complexo B",
    categoria: "Vitaminas",
    preco: 35.00,
    estoque: 25,
    imagem: "https://images.unsplash.com/photo-1576602976047-174e57a47881?q=80&w=400&h=400&auto=format&fit=crop",
    descricao: "Auxilia no metabolismo energético.",
    modoUso: "1 drágea ao dia.",
    contraindicacoes: "Hipersensibilidade aos componentes.",
    rating: 4.7,
    criadoEm: new Date().toISOString(),
  }
];